blog/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.index),
    url(r'^article/(?P<article_id>[0-9]+)$',views.article_page,name='article_page')
]

myblog/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include('blog.urls', namespace='blog')),
]

blog/models.py
from django.db import models

class Article(models.Model):
    title = models.CharField(max_length = 32,default = 'Title')
    content = models.TextField(null = True)
    
    def __str__(self):
        return self.title
    

blog/views.py
from django.http import HttpResponse
from django.shortcuts import render

from . import models


def index(request):
    articles = models.Article.objects.all()
    return render(request,'blog/index.html',{'articles':articles})

def article_page(request,article_id):
    article = models.Article.objects.get(pk=article_id)
    return render(request,'blog/article_page.html',{'article':article})

blog/templates/blog/article_page.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Insert title here</title>
</head>
<body>
	<h1>{{article.title}}</h1>
	</br>
	<h3>{{article.content}}</h3>
	</br></tr>
	<a href="">修改文章</a>
</body>
</html>

blog/templates/blog/index.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Insert title here</title>
</head>
<body>
	<h1>
		<a href="">修改文章，尝试git  pull指令</a>
	</h1>
	{%for article in articles%}
		<a href="{% url 'blog:article_page' article.id %}">{{article.title}}</a>
		<br /> 
	{%endfor%}
</body>
</html>